/**
 * Dummy Data for Development
 * Sundanese Cultural Artifacts from West Java, Indonesia
 */

import type { Artifact } from '@/types';

export const dummyArtifacts: Artifact[] = [
  {
    id: 1,
    name: 'Keris Pusaka Sunda',
    category: 'Senjata Tradisional',
    origin: 'Priangan, Jawa Barat',
    year: '1750',
    description: 'Keris pusaka Sunda dengan pamor berkualitas tinggi dan hulu berbentuk kepala naga. Diyakini memiliki kekuatan spiritual dan diwariskan turun-temurun dalam keluarga bangsawan Sunda. Keris ini menunjukkan keahlian pandai besi Sunda dalam mengolah logam.',
    image_url: '/images/artifacts/keris-sunda.jpg',
    audio_url: null,
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-01-15'),
  },
  {
    id: 2,
    name: 'Angklung Gubrag',
    category: 'Alat Musik',
    origin: 'Jasinga, Bogor',
    year: '1900',
    description: 'Angklung Gubrag adalah jenis angklung besar yang digunakan dalam upacara adat Sunda, khususnya ritual padi. Terbuat dari bambu pilihan dengan nada pentatonik. Angklung ini dimainkan secara berkelompok dalam prosesi ngaseuk (memanen padi).',
    image_url: '/images/artifacts/angklung-gubrag.jpg',
    audio_url: null,
    created_at: new Date('2024-01-16'),
    updated_at: new Date('2024-01-16'),
  },
  {
    id: 3,
    name: 'Topeng Klana',
    category: 'Seni Topeng',
    origin: 'Cirebon, Jawa Barat',
    year: '1850',
    description: 'Topeng kayu yang digunakan dalam tari topeng Cirebon. Topeng Klana menggambarkan karakter raja yang sedang jatuh cinta, dengan ekspresi wajah yang penuh emosi. Dicat dengan warna merah dan emas, menunjukkan keanggunan seni ukir Sunda.',
    image_url: '/images/artifacts/topeng-klana.jpg',
    audio_url: null,
    created_at: new Date('2024-01-17'),
    updated_at: new Date('2024-01-17'),
  },
  {
    id: 4,
    name: 'Kujang Sunda',
    category: 'Senjata Tradisional',
    origin: 'Tasikmalaya, Jawa Barat',
    year: '1800',
    description: 'Kujang adalah senjata khas dan simbol kebanggaan masyarakat Sunda. Berbentuk unik menyerupai huruf "K" dengan gagang dari kayu yang diukir indah. Kujang bukan hanya senjata, tetapi juga memiliki makna filosofis tentang ketajaman budi pekerti.',
    image_url: '/images/artifacts/kujang.jpg',
    audio_url: null,
    created_at: new Date('2024-01-18'),
    updated_at: new Date('2024-01-18'),
  },
  {
    id: 5,
    name: 'Gamelan Degung',
    category: 'Alat Musik',
    origin: 'Bandung, Jawa Barat',
    year: '1920',
    description: 'Seperangkat gamelan degung yang terdiri dari bonang, saron, dan gong. Gamelan degung memiliki nada yang lebih lembut dibanding gamelan Jawa, mencerminkan karakter halus budaya Sunda. Digunakan untuk mengiringi tari dan upacara adat.',
    image_url: '/images/artifacts/gamelan-degung.jpg',
    audio_url: null,
    created_at: new Date('2024-01-19'),
    updated_at: new Date('2024-01-19'),
  },
  {
    id: 6,
    name: 'Wayang Golek Cepot',
    category: 'Seni Wayang',
    origin: 'Bogor, Jawa Barat',
    year: '1880',
    description: 'Wayang golek kayu yang menggambarkan tokoh punakawan Cepot. Diukir dengan detail tinggi dan dicat dengan warna-warna cerah. Cepot adalah tokoh lucu yang sering memberikan nasihat bijak dalam pertunjukan wayang golek Sunda.',
    image_url: '/images/artifacts/wayang-golek-cepot.jpg',
    audio_url: null,
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-01-20'),
  },
  {
    id: 7,
    name: 'Batik Kawung Priangan',
    category: 'Tekstil',
    origin: 'Garut, Jawa Barat',
    year: '1910',
    description: 'Kain batik dengan motif kawung khas Priangan. Motif ini melambangkan kesempurnaan dan kebijaksanaan. Batik Sunda memiliki warna-warna natural dari bahan pewarna alami seperti indigo dan soga, dengan corak yang lebih sederhana namun elegan.',
    image_url: '/images/artifacts/batik-kawung.jpg',
    audio_url: null,
    created_at: new Date('2024-01-21'),
    updated_at: new Date('2024-01-21'),
  },
  {
    id: 8,
    name: 'Golok Ciomas',
    category: 'Senjata Tradisional',
    origin: 'Ciomas, Bogor',
    year: '1860',
    description: 'Golok adalah senjata tradisional Sunda yang digunakan untuk berbagai keperluan, dari pertanian hingga pertahanan diri. Golok Ciomas terkenal dengan kualitas besinya yang kuat dan tajam. Gagang terbuat dari kayu jati dengan ukiran motif Sunda.',
    image_url: '/images/artifacts/golok-ciomas.jpg',
    audio_url: null,
    created_at: new Date('2024-01-22'),
    updated_at: new Date('2024-01-22'),
  },
  {
    id: 9,
    name: 'Kendang Pencak',
    category: 'Alat Musik',
    origin: 'Sumedang, Jawa Barat',
    year: '1890',
    description: 'Kendang atau gendang yang digunakan untuk mengiringi pencak silat Sunda. Terbuat dari kayu nangka dengan kulit kambing atau sapi. Bunyi kendang pencak memiliki irama khas yang energik, membangkitkan semangat para pendekar.',
    image_url: '/images/artifacts/kendang-pencak.jpg',
    audio_url: null,
    created_at: new Date('2024-01-23'),
    updated_at: new Date('2024-01-23'),
  },
  {
    id: 10,
    name: 'Tenun Lurik Sunda',
    category: 'Tekstil',
    origin: 'Majalengka, Jawa Barat',
    year: '1925',
    description: 'Kain tenun lurik dengan pola garis-garis vertikal dan horizontal khas Sunda. Dibuat dengan alat tenun tradisional (ATBM) menggunakan benang katun. Lurik Sunda biasa digunakan untuk membuat ikat kepala atau sampur dalam tari tradisional.',
    image_url: '/images/artifacts/tenun-lurik.jpg',
    audio_url: null,
    created_at: new Date('2024-01-24'),
    updated_at: new Date('2024-01-24'),
  },
  {
    id: 11,
    name: 'Karinding Bambu',
    category: 'Alat Musik',
    origin: 'Bandung, Jawa Barat',
    year: '1940',
    description: 'Karinding adalah alat musik tiup tradisional Sunda yang terbuat dari pelepah bambu atau daun lontar. Dimainkan dengan cara ditiup sambil memetik lidah karinding. Menghasilkan suara unik yang dipercaya dapat mengusir hama padi.',
    image_url: '/images/artifacts/karinding.jpg',
    audio_url: null,
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-01-25'),
  },
  {
    id: 12,
    name: 'Badak Beureum (Dodol Garut)',
    category: 'Wadah Tradisional',
    origin: 'Garut, Jawa Barat',
    year: '1905',
    description: 'Wadah keramik tradisional berbentuk unik yang digunakan untuk menyimpan dodol Garut. Dinamakan "Badak Beureum" karena bentuknya menyerupai badak dan berwarna merah. Keramik ini dibuat dengan teknik pembakaran tradisional dan memiliki nilai historis tinggi.',
    image_url: '/images/artifacts/badak-beureum.jpg',
    audio_url: null,
    created_at: new Date('2024-01-26'),
    updated_at: new Date('2024-01-26'),
  },
];
